safe:        false
auto:        false
permalink:   pretty

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false

gems:
  - jemoji
  - jekyll-sitemap

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
